apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: frontend-progest-base
  title: "frontend-progest-base"
  description: "Sistema frontend-progest-base analisado automaticamente"
  annotations:
    github.com/project-slug: "chvcti/frontend-progest-base"
    backstage.io/techdocs-ref: "dir:."
spec:
  owner: user:chvcti
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: traefik
  title: "Traefik"
  description: "proxy reverso projetado para gerenciar e rotear o tráfego de redes e microsserviços de forma automatizada"
  tags:
    - resource
  annotations:
    github.com/project-slug: "chvcti/frontend-progest-base"
spec:
  type: database
  lifecycle: experimental
  owner: user:ifba
  system: frontend-progest-base
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: frontend-progest-base-frontend
  title: "frontend-progest-base-frontend"
  description: "Componente frontend-progest-base-frontend (website)"
  tags:
    - vue-js
  annotations:
    github.com/project-slug: "chvcti/frontend-progest-base"
    backstage.io/techdocs-ref: "dir:."
spec:
  type: website
  lifecycle: experimental
  owner: user:chvcti
  system: frontend-progest-base
  dependsOn:
    - resource:default/traefik