apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: progest-frontend-web
  title: ProGest Frontend Web
  description: Aplicação Web SPA (Single Page Application) do Sistema Hospitalar ProGest, desenvolvida em Vue.js 3, Vite e TailwindCSS para gestão de pedidos, dispensação e controle de estoque hospitalar.
  tags:
    - vue
    - vue3
    - vite
    - tailwindcss
    - spa
    - frontend
    - healthcare
  links:
    - url: https://github.com/progest-hgvca/frontend-progest-base
      title: Repositório GitHub
      icon: github
    - url: http://18.230.26.35/
      title: Aplicação Web Homologação (AWS)
      icon: web
    - url: http://app.localhost/
      title: Aplicação Web Local (Docker)
      icon: dashboard
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: progest-hgvca/frontend-progest-base
spec:
  type: website
  lifecycle: production
  owner: squad-progest-hgvc
  system: progest-hospitalar
  consumesApis:
    - progest-rest-api
  dependsOn:
    - component:progest-backend-api
    - component:traefik-proxy
